common/urls.py
from django.conf.urls import patterns, include, url
from common.views import *


urlpatterns = patterns('',
    url(r'^register/$', register, name='register'),
    url(r'^login/$', connexion, name='connexion'),
    url(r'^logout/$', deconnexion, name='deconnexion'),
)

permission/urls.py
from django.conf.urls import patterns, include, url
from permission.views import *


urlpatterns = patterns('',
    url(r'^home/$', home, name="home"),
    url(r'^teachers/$', teachers, name="teachers"),
    url(r'^teachers2/$', teachers, name="teachers2"),
    url(r'^students/$', students, name="students"),
)

webmath/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy

from django.views.generic.base import RedirectView


urlpatterns = patterns('', 
    url(r'^admin/', include(admin.site.urls)),
    url(r'^common/', include('common.urls', namespace="common")),
    url(r'^permission/', include('permission.urls', namespace="permission")),
    url(r'^$' , RedirectView.as_view(pattern_name='common.connexion')),
)

common/models.py
from django.db import models
from django.contrib.auth.models import User

class BaseProfile(models.Model):
    user = models.OneToOneField(User)
    avatar = models.ImageField(null=True, blank=True, upload_to="avatars/")
        
    class Meta:
        abstract = True

class Teacher(BaseProfile):

    def __str__(self):
        return "Professeur {0}".format(self.user.username)

class Student(BaseProfile):

    def __str__(self):
        return "Etudiant {0}".format(self.user.username)

permission/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.forms.extras.widgets import *

# pour supprimer les doubles points dans les formulaires générés, : https://github.com/torchbox/wagtail/issues/130

class LoginForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur", max_length=30)
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)


class RegisterForm(forms.Form):
    username = forms.CharField(label="Nom d'utilisateur", widget= forms.TextInput(attrs={'class' : 'form-control'}))
    password = forms.CharField(label='Mot de passe', widget=forms.PasswordInput(attrs={'class' : 'form-control'}))
    mail = forms.CharField(label='E-mail', widget=forms.EmailInput(attrs={'class' : 'form-control'}))
    account_type = forms.ChoiceField(label='Type de compte', choices=(
        ("teacher", "Professeur"),
        ("student", "Étudiant"),
        ))

common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from common.forms import LoginForm, RegisterForm
from django.core.urlresolvers import reverse
from common.models import *
from django.contrib.auth.models import User
from django.http import HttpResponse

def connexion(request):
    erreur = False
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
            else:
                erreur = True
    else:
        form = LoginForm()
        
    return render(request, "common/login.html", locals())
    
def deconnexion(request):
    logout(request)
    return redirect('common:connexion')
    
    
def register(request):
    if request.method == "POST":
        registerform = RegisterForm(data=request.POST)
        
        if registerform.is_valid():
            username = registerform.cleaned_data["username"]
            password = registerform.cleaned_data["password"]
            mail = registerform.cleaned_data["mail"]
            
            try:
                User.objects.get(username=username)
            except User.DoesNotExist:
                user = User.objects.create_user(username, mail, password)
                user.save()
                
                account_model = None # Modèle à instancier pour créer le compte
                
                if registerform.cleaned_data["account_type"] == "student":
                    account_model = Student # Le modèle à utiliser est Student
                    
                elif registerform.cleaned_data["account_type"] == "teacher":
                    account_model = Teacher # Le modèle à utiliser est Teacher
                    
                account = account_model() # Instanciation du modèle
                account.user = user # Liaison au compte user
                account.save()
                
                return redirect('common:connexion')
            except Exception as e:
                return HttpResponse("Erreur non gérée : {}".format(str(e)))

    else:
        registerform = RegisterForm()
        
    return render(request, "common/register.html", {'registerform' : registerform})

permission/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, user_passes_test
from common.auth_utils import *

@login_required
def home(request):
    return render(request, 'permission/home.html', locals())

@login_required
@user_passes_test(is_teacher)
def teachers(request):
    return render(request, 'permission/teachers.html')
 
@login_required
@user_passes_test(is_student)
def students(request):
    return render(request, 'permission/students.html')

@teacher_required
def teachers2(request):
    return render(request, 'permission/teachers.html')

common/templates/common/login.html
<!DOCTYPE html>

<head>
    
    <meta charset="utf-8" />
    <title>Connexion</title>
    
</head>
<body>
    
    <h1>Veuillez remplir les champs suivants:</h1>
    
    <button onclick="window.location.href='{% url 'common:register' %}'">S'inscrire</button>
    
    {% if erreur %}
    <p><strong>Connexion échouée</strong></p>
    {% endif %}
    
    {% if user.is_authenticated %}
    Connexion réussie! Bienvenue {{ user.username }}!
    <form method="post" action="{% url 'common:deconnexion' %}">
        {% csrf_token %}
        <button type="submit" />Se déconnecter</button>
    </form>
    
    {% else %}
    <form class="formLogin" method="post" action=".">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Se connecter"/>
    </form>
    {% endif %}
        
</body>

common/templates/common/register.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
    </head>
    <body>
        <form method="POST" action="{% url 'common:register' %}">
            {% csrf_token %}
            {{ registerform }}
            <button type="submit" class="btn btn-primary">Envoyer</button>
        </form>
    </body>
</html>

    

permission/templates/permission/home.html
Home

permission/templates/permission/students.html
Students

permission/templates/permission/teachers.html
Teachers